---
abstract: 'Calculate points in the Julia set'
author:
  - 'Jeffrey T. Palmer <jtpalmer@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Fractal-Julia
requires:
  XSLoader: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/jtpalmer/Math-Fractal-Julia/issues
  homepage: https://github.com/jtpalmer/Math-Fractal-Julia
  repository: https://github.com/jtpalmer/Math-Fractal-Julia.git
version: 0.000003
